// Seeds a database with the admin account and club data.
//
// - By default: SYNTHETIC demo data (prisma/demo-data.json, generated by
//   scripts/data/generate-demo-data.mjs). No real people.
// - Real club data never lives in git (Gate #1 A15). To load it, point
//   SEED_DATA_FILE at the decrypted JSON outside the repository (and
//   optionally SEED_HISTORICAL_LOANS_FILE); see README "Real club data".
//
// Refuses to load demo data into a production database.
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'
import { DEFAULT_ADMIN_EMAIL } from '../src/lib/brand'
import { adoptPortalLogins } from '../src/modules/auth/memberLogins'

const prisma = new PrismaClient()

type SeedData = {
  members: any[]
  yearlyTotals: any[]
  contributions: any[]
  loans: any[]
  loanPayments: any[]
  historicalLoans?: any[]
}

function loadData(): { data: SeedData; label: string } {
  const file = process.env.SEED_DATA_FILE
  if (file) {
    const data = JSON.parse(readFileSync(file, 'utf8')) as SeedData
    const historicalFile = process.env.SEED_HISTORICAL_LOANS_FILE
    if (historicalFile) data.historicalLoans = JSON.parse(readFileSync(historicalFile, 'utf8'))
    return { data, label: `club data from ${file}` }
  }
  if (process.env.NODE_ENV === 'production' && process.env.SEED_DEMO_DATA !== '1') {
    throw new Error('Refusing to load demo data in production. Set SEED_DATA_FILE, or SEED_DEMO_DATA=1 for a demo server.')
  }
  const data = JSON.parse(readFileSync(path.join(__dirname, 'demo-data.json'), 'utf8')) as SeedData
  return { data, label: 'SYNTHETIC demo data (no real people)' }
}

async function main() {
  const { data, label } = loadData()
  console.log(`🌱 Seeding ${label}...`)

  // Default admin account (Super Admin; sets up two-factor at first sign-in)
  const adminPassword = process.env.ADMIN_SEED_PASSWORD
  if (!adminPassword || adminPassword.length < 12) {
    throw new Error('Set ADMIN_SEED_PASSWORD (at least 12 characters) before seeding.')
  }
  const hashed = await bcrypt.hash(adminPassword, 10)
  const adminEmail = process.env.ADMIN_SEED_EMAIL || DEFAULT_ADMIN_EMAIL
  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {},
    create: { kind: 'staff', email: adminEmail, name: 'Millionaires Club Admin', passwordHash: hashed },
  })
  await prisma.staffRoleAssignment.upsert({
    where: { userId_role: { userId: admin.id, role: 'super_admin' } },
    update: {},
    create: { userId: admin.id, role: 'super_admin' },
  })
  console.log('✓ Admin account (Super Admin; sets up two-factor authentication at first sign-in)')

  for (const m of data.members) {
    await prisma.member.upsert({
      where: { id: m.id },
      update: {},
      create: {
        ...m,
        joinDate: new Date(m.joinDate),
        lastContributionDate: m.lastContributionDate ? new Date(m.lastContributionDate) : null,
      },
    })
  }
  console.log(`✓ ${data.members.length} members`)
  // A data file from before M8 carries portal passwords on the members: they become logins.
  const logins = await adoptPortalLogins(prisma)
  if (logins) console.log(`✓ ${logins} member portal logins`)

  for (const y of data.yearlyTotals) {
    await prisma.yearlyTotal.upsert({
      where: { memberId_year: { memberId: y.memberId, year: y.year } },
      update: {},
      create: y,
    })
  }
  console.log(`✓ ${data.yearlyTotals.length} yearly totals`)

  for (const c of data.contributions) {
    await prisma.contribution.upsert({
      where: { transactionId: c.transactionId },
      update: {},
      create: { ...c, paymentDate: new Date(c.paymentDate), amountCents: BigInt(Math.round(c.amount * 100)) },
    })
  }
  console.log(`✓ ${data.contributions.length} contributions`)

  for (const l of data.loans) {
    await prisma.loan.upsert({
      where: { loanId: l.loanId },
      update: {},
      create: {
        ...l,
        lifecycle: l.status === 'Paid Off' ? 'paid_off' : l.status === 'Cancelled' ? 'cancelled' : 'disbursed',
        loanDate: new Date(l.loanDate),
        endDate: l.endDate ? new Date(l.endDate) : null,
        nextDueDate: l.nextDueDate ? new Date(l.nextDueDate) : null,
      },
    })
  }
  console.log(`✓ ${data.loans.length} loans`)

  for (const p of data.loanPayments) {
    await prisma.loanPayment.upsert({
      where: { paymentId: p.paymentId },
      update: {},
      create: { ...p, paymentDate: new Date(p.paymentDate) },
    })
  }
  console.log(`✓ ${data.loanPayments.length} loan payments`)

  for (const loan of data.historicalLoans ?? []) {
    await prisma.historicalLoan.upsert({
      where: { loanId: loan.loanId },
      update: {},
      create: {
        ...loan,
        loanDate: new Date(loan.loanDate),
        endDate: loan.endDate ? new Date(loan.endDate) : null,
      },
    })
  }
  console.log(`✓ ${data.historicalLoans?.length ?? 0} historical loans`)

  console.log('\n✅ Done!')
  console.log(`📧 Login: ${adminEmail}`)
  console.log('🔑 Password: the value of ADMIN_SEED_PASSWORD')
}

main()
  .catch((err) => {
    console.error(err instanceof Error ? err.message : err)
    process.exitCode = 1
  })
  .finally(() => prisma.$disconnect())
